language: node_js
node_js:
  - "12.16.1"

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: "npm run test"
    - stage: deploy
      name: "Deploy to NPM"

deploy:
  provider: npm
  - script: "npm run build"
  email: $NPM_EMAIL_ADDRESS
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    branch: master