language: node_js
node_js:
  - '12.16.1'

jobs:
  include:
    - stage: test
      name: 'Unit Tests'
      script: 'npm run test'
    - stage: deploy
      script: 'npm run build'
      name: 'Deploy to NPM'

deploy:
  provider: npm
  email: $NPM_EMAIL_ADDRESS
  api_key: $NPM_AUTH_TOKEN
  cleanup: true
  tag: next
  on:
    branch: master
    tags: true
