language: node_js
node_js:
  - '12.13'

branches:
  except:
    - develop

jobs:
  include:
    - stage: test
      name: 'Unit Tests'
      script:
        - npm run test
      after_success: npm run coverage
    - stage: deploy
      name: 'Deploy to NPM'
      before_deploy:
        - npm install
        - npm run build
      deploy:
        provider: npm
        email: $NPM_EMAIL_ADDRESS
        api_token: $NPM_AUTH_TOKEN
        cleanup: true
        on:
          branch: master
