language: node_js
node_js:
  - '12.13'

branches:
  except:
    - develop

jobs:
  include:
    - stage: test
      name: 'Unit Tests'
      script: 'npm run test'
    - stage: deploy
      name: 'Deploy to NPM'
      deploy:
        provider: npm
        email: $NPM_EMAIL_ADDRESS
        api_key: $NPM_AUTH_TOKEN
        cleanup: true
        on:
          branch: master
